/**
 * @fileoverview gRPC-Web generated client stub for Questions
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: questions.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.Questions = require('./questions_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.Questions.QuestionsClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.Questions.QuestionsPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Questions.AddRequest,
 *   !proto.Questions.AddResponse>}
 */
const methodDescriptor_Questions_Add = new grpc.web.MethodDescriptor(
  '/Questions.Questions/Add',
  grpc.web.MethodType.UNARY,
  proto.Questions.AddRequest,
  proto.Questions.AddResponse,
  /**
   * @param {!proto.Questions.AddRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Questions.AddResponse.deserializeBinary
);


/**
 * @param {!proto.Questions.AddRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Questions.AddResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Questions.AddResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.Questions.QuestionsClient.prototype.add =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Questions.Questions/Add',
      request,
      metadata || {},
      methodDescriptor_Questions_Add,
      callback);
};


/**
 * @param {!proto.Questions.AddRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Questions.AddResponse>}
 *     Promise that resolves to the response
 */
proto.Questions.QuestionsPromiseClient.prototype.add =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Questions.Questions/Add',
      request,
      metadata || {},
      methodDescriptor_Questions_Add);
};


module.exports = proto.Questions;

